import type { Metadata } from "next";
import { Archivo, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";
import Footer from "@/app/components/layout/Footer";
import WhatsAppFab from "@/app/components/layout/WhatsAppFab";
import IframeHeightReporter from "@/app/components/layout/IframeHeightReporter";
import CustomCursor from "@/app/components/layout/CustomCursor";
import ScrollProgress from "@/app/components/ui/ScrollProgress";

// Brand fonts — self-hosted via next/font (no render-blocking Google request).
// The CSS variables below feed the Tailwind theme (--font-sans / --font-display).
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["600", "700", "800", "900"],
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"
  ),
  title: {
    default: "CodeXmattriX — Envision. Design. Code.",
    template: "%s — CodeXmattriX",
  },
  description:
    "Custom web, app & software development agency. We design high-performing websites, apps, and software that convert — for healthcare, cannabis, and growing US brands.",
  // Favicon — the brand icon supplied by the CMS, bundled locally so it never
  // depends on the CMS being reachable:
  //   public/images/favicon.webp → modern browsers (declared here)
  //   app/favicon.ico            → legacy fallback (Next.js file convention)
  //   app/apple-icon.png         → iOS / iPadOS home screen (file convention)
  // Regenerate the derived icons with `node scripts/make-favicons.mjs`.
  icons: {
    icon: [{ url: "/images/favicon.webp", type: "image/webp" }],
    // iOS / iPadOS home screen — same artwork, declared explicitly so the
    // link is always emitted (the PNG is generated by make-favicons.mjs).
    apple: [{ url: "/apple-icon.png", type: "image/png", sizes: "180x180" }],
  },
  openGraph: {
    type: "website",
    siteName: "CodeXmattriX",
    title: "CodeXmattriX — Envision. Design. Code.",
    description:
      "Custom web, app & software development agency — healthcare, CBD & growing US brands.",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${archivo.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-white font-sans text-ink">
        <IframeHeightReporter />
        <ScrollProgress />
        <CustomCursor />
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <WhatsAppFab />
      </body>
    </html>
  );
}
